### ISSUE TITLE
Gitlab URLs are ignored 

### ISSUE THREAD

**Issue by hidmic** [clalancette/ros_changelog_from_pkgs#1]
The current script is unable to generate Gitlab URLs. While core packages in repositories like https://gitlab.com/ros-tracing/ros2_tracing can still be scrapped, these end up without a link to the source CHANGELOG.rst file.

**Comment by clalancette** [comment]
All right, this should be fixed by 375b37ef9211d5721504d89a537ab1a27c3340fb, so closing this.
